---
datadog:
  securityContext: {}
  logs:
    enabled: true
    containerCollectAll: true
    containerCollectUsingFiles: true
  confd:
    tcp_check.yaml: |-
      init_config:
      instances:
        - name: accounts-db
          host: accounts-db.default
          port: 5432
          collect_response_time: true 
        - name: balance-reader
          host: balancereader.default
          port: 8080
          collect_response_time: true 
        - name: contacts
          host: contacts.default
          port: 8080
          collect_response_time: true 
        - name: frontend
          host: frontend.default
          port: 80
          collect_response_time: true 
        - name: ledger-db
          host: ledger-db.default
          port: 5432
          collect_response_time: true 
        - name: ledger-writer
          host: ledgerwriter.default
          port: 8080
          collect_response_time: true 
        - name: transaction-history
          host: transactionhistory.default
          port:  8080
          collect_response_time: true 
        - name: userservice
          host: userservice.default
          port: 8080
          collect_response_time: true 
  processAgent:
    enabled: true
    processCollection: true