{
 "title": "Boutique Shop",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  { "title": "Node Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Active Nodes",
   "type": "stat",
   "description": "The current number of nodes in the cluster.",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_status_condition{condition=\"Ready\", status=\"true\"}==1)"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    { "expr": "instance:node_cpu:rate:sum", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "instance:node_memory_utilisation:ratio",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Disk usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{mountpoint=\"/\",fstype!=\"rootfs\"} * 100) / node_filesystem_size_bytes{mountpoint=\"/\",fstype!=\"rootfs\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "System IO",
   "type": "timeseries",
   "description": "Reads and writes per second",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (instance) (rate(node_disk_reads_completed_total[1m]))",
     "legendFormat": "{{instance}} reads"
    },
    {
     "expr": "sum by (instance) (rate(node_disk_writes_completed_total[1m]))",
     "legendFormat": "{{instance}} writes"
    }
   ]
  },
  {
   "title": "Network activity",
   "type": "timeseries",
   "description": "Packets sent and received per second",
   "gridPos": { "h": 8, "w": 12, "x": 10, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum by (instance) (rate(node_network_receive_packets_total[5m]))",
     "legendFormat": "{{instance}} rcv"
    },
    {
     "expr": "sum by (instance) (rate(node_network_transmit_packets_total[5m]))",
     "legendFormat": "{{instance}} sent"
    }
   ]
  },
  { "title": "Kubernetes Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Pods (ready)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_ready{namespace=\"default\", condition=\"true\"})"
    }
   ]
  },
  {
   "title": "Pod Network Bytes Received",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 9, "x": 4, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by (pod) (irate(container_network_receive_bytes_total{namespace=\"default\"}[1m]))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Pod Network Bytes Sent",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 9, "x": 13, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by (pod) (irate(container_network_transmit_bytes_total{namespace=\"default\"}[1m]))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Pods (waiting)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_ready{namespace=\"default\", condition=\"false\"})"
    }
   ]
  },
  {
   "title": "Container restarts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "sum by (container) (rate(kube_pod_container_status_restarts_total{namespace=\"default\"}[5m]))",
     "legendFormat": "{{container}}"
    }
   ]
  }
 ]
}