grafana:
  grafana.ini:
    server:
      domain: group[[GROUP_ID]].gremlinbootcamp.com
      root_url: "%(protocol)s://%(domain)s/grafana"
      serve_from_sub_path: true
  ingress:
    enabled: true
    hosts:
      - "group[[GROUP_ID]].gremlinbootcamp.com"
    path: "/grafana"
