---
datadog:
  securityContext: {}
  logs:
    enabled: true
    containerCollectAll: true
    containerCollectUsingFiles: true
  confd:
    tcp_check.yaml: |-
      init_config:
      instances:
        - name: adservice
          host: adservice.default
          port: 9555 
          collect_response_time: true 
        - name: cartservice
          host: cartservice.default
          port: 7070 
          collect_response_time: true 
        - name: checkoutservice
          host: checkoutservice.default
          port: 5050 
          collect_response_time: true 
        - name: currencyservice
          host: currencyservice.default
          port: 7000 
          collect_response_time: true 
        - name: emailservice
          host: emailservice.default
          port: 5000 
          collect_response_time: true 
        - name: frontend
          host: frontend.default
          port: 80
          collect_response_time: true 
        - name: paymentservice
          host: paymentservice.default
          port: 50051
          collect_response_time: true 
        - name: productcatalogservice
          host: productcatalogservice.default
          port: 3550 
          collect_response_time: true 
        - name: recommendationservice
          host: recommendationservice.default
          port: 8080 
          collect_response_time: true 
        - name: redis
          host: redis.default-cart
          port: 6379 
          collect_response_time: true 
        - name: shippingservice
          host: shippingservice.default
          port: 50051
          collect_response_time: true 
  processAgent:
    enabled: true
    processCollection: true